package es.eina.tfg.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import es.eina.tfg.service.persistence.UserAndRoutePK;

import java.io.Serializable;

/**
 * The base model interface for the UserAndRoute service. Represents a row in the &quot;GL_UserAndRoute&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link es.eina.tfg.model.impl.UserAndRouteModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link es.eina.tfg.model.impl.UserAndRouteImpl}.
 * </p>
 *
 * @author adelrioj
 * @see UserAndRoute
 * @see es.eina.tfg.model.impl.UserAndRouteImpl
 * @see es.eina.tfg.model.impl.UserAndRouteModelImpl
 * @generated
 */
public interface UserAndRouteModel extends BaseModel<UserAndRoute> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a user and route model instance should use the {@link UserAndRoute} interface instead.
     */

    /**
     * Returns the primary key of this user and route.
     *
     * @return the primary key of this user and route
     */
    public UserAndRoutePK getPrimaryKey();

    /**
     * Sets the primary key of this user and route.
     *
     * @param primaryKey the primary key of this user and route
     */
    public void setPrimaryKey(UserAndRoutePK primaryKey);

    /**
     * Returns the id user of this user and route.
     *
     * @return the id user of this user and route
     */
    public long getIdUser();

    /**
     * Sets the id user of this user and route.
     *
     * @param idUser the id user of this user and route
     */
    public void setIdUser(long idUser);

    /**
     * Returns the id route of this user and route.
     *
     * @return the id route of this user and route
     */
    public long getIdRoute();

    /**
     * Sets the id route of this user and route.
     *
     * @param idRoute the id route of this user and route
     */
    public void setIdRoute(long idRoute);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(es.eina.tfg.model.UserAndRoute userAndRoute);

    @Override
    public int hashCode();

    @Override
    public CacheModel<es.eina.tfg.model.UserAndRoute> toCacheModel();

    @Override
    public es.eina.tfg.model.UserAndRoute toEscapedModel();

    @Override
    public es.eina.tfg.model.UserAndRoute toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
