package es.eina.tfg.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import es.eina.tfg.service.persistence.UserSelectedRoutesPK;

import java.io.Serializable;

/**
 * The base model interface for the UserSelectedRoutes service. Represents a row in the &quot;GL_UserSelectedRoutes&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link es.eina.tfg.model.impl.UserSelectedRoutesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link es.eina.tfg.model.impl.UserSelectedRoutesImpl}.
 * </p>
 *
 * @author adelrioj
 * @see UserSelectedRoutes
 * @see es.eina.tfg.model.impl.UserSelectedRoutesImpl
 * @see es.eina.tfg.model.impl.UserSelectedRoutesModelImpl
 * @generated
 */
public interface UserSelectedRoutesModel extends BaseModel<UserSelectedRoutes> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a user selected routes model instance should use the {@link UserSelectedRoutes} interface instead.
     */

    /**
     * Returns the primary key of this user selected routes.
     *
     * @return the primary key of this user selected routes
     */
    public UserSelectedRoutesPK getPrimaryKey();

    /**
     * Sets the primary key of this user selected routes.
     *
     * @param primaryKey the primary key of this user selected routes
     */
    public void setPrimaryKey(UserSelectedRoutesPK primaryKey);

    /**
     * Returns the user ID of this user selected routes.
     *
     * @return the user ID of this user selected routes
     */
    public long getUserId();

    /**
     * Sets the user ID of this user selected routes.
     *
     * @param userId the user ID of this user selected routes
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this user selected routes.
     *
     * @return the user uuid of this user selected routes
     * @throws SystemException if a system exception occurred
     */
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this user selected routes.
     *
     * @param userUuid the user uuid of this user selected routes
     */
    public void setUserUuid(String userUuid);

    /**
     * Returns the route ID of this user selected routes.
     *
     * @return the route ID of this user selected routes
     */
    public long getRouteId();

    /**
     * Sets the route ID of this user selected routes.
     *
     * @param routeId the route ID of this user selected routes
     */
    public void setRouteId(long routeId);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        es.eina.tfg.model.UserSelectedRoutes userSelectedRoutes);

    @Override
    public int hashCode();

    @Override
    public CacheModel<es.eina.tfg.model.UserSelectedRoutes> toCacheModel();

    @Override
    public es.eina.tfg.model.UserSelectedRoutes toEscapedModel();

    @Override
    public es.eina.tfg.model.UserSelectedRoutes toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
