/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package es.eina.tfg.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the UserAdditionalData service. Represents a row in the &quot;GL_UserAdditionalData&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link es.eina.tfg.model.impl.UserAdditionalDataModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link es.eina.tfg.model.impl.UserAdditionalDataImpl}.
 * </p>
 *
 * @author adelrioj
 * @see UserAdditionalData
 * @see es.eina.tfg.model.impl.UserAdditionalDataImpl
 * @see es.eina.tfg.model.impl.UserAdditionalDataModelImpl
 * @generated
 */
public interface UserAdditionalDataModel extends BaseModel<UserAdditionalData> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user additional data model instance should use the {@link UserAdditionalData} interface instead.
	 */

	/**
	 * Returns the primary key of this user additional data.
	 *
	 * @return the primary key of this user additional data
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user additional data.
	 *
	 * @param primaryKey the primary key of this user additional data
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user ID of this user additional data.
	 *
	 * @return the user ID of this user additional data
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user additional data.
	 *
	 * @param userId the user ID of this user additional data
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user additional data.
	 *
	 * @return the user uuid of this user additional data
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this user additional data.
	 *
	 * @param userUuid the user uuid of this user additional data
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the register type of this user additional data.
	 *
	 * @return the register type of this user additional data
	 */
	@AutoEscape
	public String getRegisterType();

	/**
	 * Sets the register type of this user additional data.
	 *
	 * @param registerType the register type of this user additional data
	 */
	public void setRegisterType(String registerType);

	/**
	 * Returns the weight of this user additional data.
	 *
	 * @return the weight of this user additional data
	 */
	public int getWeight();

	/**
	 * Sets the weight of this user additional data.
	 *
	 * @param weight the weight of this user additional data
	 */
	public void setWeight(int weight);

	/**
	 * Returns the height of this user additional data.
	 *
	 * @return the height of this user additional data
	 */
	public int getHeight();

	/**
	 * Sets the height of this user additional data.
	 *
	 * @param height the height of this user additional data
	 */
	public void setHeight(int height);

	/**
	 * Returns the sms counter of this user additional data.
	 *
	 * @return the sms counter of this user additional data
	 */
	public long getSmsCounter();

	/**
	 * Sets the sms counter of this user additional data.
	 *
	 * @param smsCounter the sms counter of this user additional data
	 */
	public void setSmsCounter(long smsCounter);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		es.eina.tfg.model.UserAdditionalData userAdditionalData);

	@Override
	public int hashCode();

	@Override
	public CacheModel<es.eina.tfg.model.UserAdditionalData> toCacheModel();

	@Override
	public es.eina.tfg.model.UserAdditionalData toEscapedModel();

	@Override
	public es.eina.tfg.model.UserAdditionalData toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}