package es.eina.tfg.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import es.eina.tfg.model.DeviceAndSensor;
import es.eina.tfg.service.DeviceAndSensorLocalServiceUtil;

/**
 * The extended model base implementation for the DeviceAndSensor service. Represents a row in the &quot;GL_DeviceAndSensor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DeviceAndSensorImpl}.
 * </p>
 *
 * @author adelrioj
 * @see DeviceAndSensorImpl
 * @see es.eina.tfg.model.DeviceAndSensor
 * @generated
 */
public abstract class DeviceAndSensorBaseImpl extends DeviceAndSensorModelImpl
    implements DeviceAndSensor {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a device and sensor model instance should use the {@link DeviceAndSensor} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            DeviceAndSensorLocalServiceUtil.addDeviceAndSensor(this);
        } else {
            DeviceAndSensorLocalServiceUtil.updateDeviceAndSensor(this);
        }
    }
}
