package es.eina.tfg.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import es.eina.tfg.model.Device;
import es.eina.tfg.service.DeviceLocalServiceUtil;

/**
 * The extended model base implementation for the Device service. Represents a row in the &quot;GL_Device&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DeviceImpl}.
 * </p>
 *
 * @author adelrioj
 * @see DeviceImpl
 * @see es.eina.tfg.model.Device
 * @generated
 */
public abstract class DeviceBaseImpl extends DeviceModelImpl implements Device {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a device model instance should use the {@link Device} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            DeviceLocalServiceUtil.addDevice(this);
        } else {
            DeviceLocalServiceUtil.updateDevice(this);
        }
    }
}
