package es.eina.tfg.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import es.eina.tfg.model.Route;
import es.eina.tfg.service.RouteLocalServiceUtil;

/**
 * The extended model base implementation for the Route service. Represents a row in the &quot;GL_Route&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RouteImpl}.
 * </p>
 *
 * @author adelrioj
 * @see RouteImpl
 * @see es.eina.tfg.model.Route
 * @generated
 */
public abstract class RouteBaseImpl extends RouteModelImpl implements Route {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a route model instance should use the {@link Route} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            RouteLocalServiceUtil.addRoute(this);
        } else {
            RouteLocalServiceUtil.updateRoute(this);
        }
    }
}
