package es.eina.tfg.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import es.eina.tfg.model.RouteLocation;
import es.eina.tfg.service.RouteLocationLocalServiceUtil;

/**
 * The extended model base implementation for the RouteLocation service. Represents a row in the &quot;GL_RouteLocation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RouteLocationImpl}.
 * </p>
 *
 * @author adelrioj
 * @see RouteLocationImpl
 * @see es.eina.tfg.model.RouteLocation
 * @generated
 */
public abstract class RouteLocationBaseImpl extends RouteLocationModelImpl
    implements RouteLocation {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a route location model instance should use the {@link RouteLocation} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            RouteLocationLocalServiceUtil.addRouteLocation(this);
        } else {
            RouteLocationLocalServiceUtil.updateRouteLocation(this);
        }
    }
}
