package es.eina.tfg.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import es.eina.tfg.model.UserAndEvent;
import es.eina.tfg.service.UserAndEventLocalServiceUtil;

/**
 * The extended model base implementation for the UserAndEvent service. Represents a row in the &quot;GL_UserAndEvent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UserAndEventImpl}.
 * </p>
 *
 * @author adelrioj
 * @see UserAndEventImpl
 * @see es.eina.tfg.model.UserAndEvent
 * @generated
 */
public abstract class UserAndEventBaseImpl extends UserAndEventModelImpl
    implements UserAndEvent {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a user and event model instance should use the {@link UserAndEvent} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            UserAndEventLocalServiceUtil.addUserAndEvent(this);
        } else {
            UserAndEventLocalServiceUtil.updateUserAndEvent(this);
        }
    }
}
